defaults:
  - _self_

datamodule:
  _target_: birdset.datamodule.birdset_datamodule.BirdSetDataModule
  dataset:
    data_dir: /home/rantjuschin/data_birdset/HSN
    hf_path: DBD-research-group/BirdSet
    hf_name: HSN
    classlimit: null
    eventlimit: null
    task: multilabel
    subset: null
    sampling_rate: 32000
    n_workers: 3
    val_split: 0.2
    class_weights_loss: null
    class_weights_sampler: null
    seed: 42

sample_length: 5
sample_padding: True
embeddings_save_path: /home/rantjuschin/bachelor-project/datasets/HSN/perch_embeddings/
