defaults:
  - _self_

dataset:
  data_dir: /mnt/stud/work/rantjuschin/datasets/indexed/XCL/
  hf_path: DBD-research-group/BirdSet
  hf_name: XCL 
  sampling_rate: 32_000
  num_classes: 9_736

sample_length: 5
padding_value: 0
batch_size: 32
embeddings_save_path: /mnt/stud/work/rantjuschin/datasets/embedded/perch/XCL

