defaults:
  - _self_

dataset:
  data_dir: /mnt/stud/work/rantjuschin/datasets/indexed/XCL/
  hf_path: DBD-research-group/BirdSet
  hf_name: XCL 
  sampling_rate: 32_000
  num_classes: 9_736

transforms:
  model_type: "vision"
  max_length: 5
  preprocessor:
    n_fft: 1024
    hop_length: 320
    power: 2.0
    mel_scale:
      n_mels: 128
      n_stft: 513
    mean: -19.107
    std: 13.098
    #mean: -15.854 # Mean of XCM: -15.854 ; Mean of XCL: -19.107
    #std: 12.911 # Standard deviation of XCM: 12.911 ; Standard deviation of XCL: 13.098

sample_length: 5
sample_padding: True
embeddings_save_path: /mnt/stud/work/rantjuschin/datasets/embedded/convnext/XCL

